apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-location-server
  name: grpc-location-server
spec:
  ports:
  - name: "5022"
    port: 5022
    targetPort: 5022
    protocol: TCP
    nodePort: 30022
  selector:
    service: grpc-location-server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc-location-server
  name: grpc-location-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpc-location-server
  template:
    metadata:
      labels:
        service: grpc-location-server
    spec:
      containers:
      - image: leoadams/grpc-location-server:latest
        name: grpc-location-server
        ports:
        - containerPort: 5022
          protocol: TCP
        #imagePullPolicy: Never
        #imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      #restartPolicy: Always