apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-grpc-server
  name: location-grpc-server
spec:
  ports:
  - name: "5018"
    port: 5018
    targetPort: 5018
    protocol: TCP
    nodePort: 30018
  selector:
    service: location-grpc-server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-grpc-server
  name: location-grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-grpc-server
  template:
    metadata:
      labels:
        service: location-grpc-server
    spec:
      containers:
      - image: leoadams/location-grpc-server:latest
        name: location-grpc-server
        ports:
        - containerPort: 5018
          protocol: TCP
        imagePullPolicy: IfNotPresent
        #imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      #restartPolicy: Always