# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     service: person-kafka-producer
#   name: person-kafka-producer
# spec:
#   # ports:
#   # - name: "5005"
#   #   port: 5005
#   #   targetPort: 5005
#   #   nodePort: 30015
#   selector:
#     service: person-kafka-producer
#   # type: NodePort
# # ---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: test-client
  name: test-client
spec:
  replicas: 1
  selector:
    matchLabels:
      service: test-client
  template:
    metadata:
      labels:
        service: test-client
    spec:
      containers:
      - image: leoadams/test-client:latest
        name: test-client
        imagePullPolicy: IfNotPresent
        # env:
        # - name: DB_USERNAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-env
        #       key: DB_USERNAME
        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secret
        #       key: DB_PASSWORD
        # - name: DB_NAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-env
        #       key: DB_NAME
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-env
        #       key: DB_HOST
        # - name: DB_PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-env
        #       key: DB_PORT
      #restartPolicy: Never
