apiVersion: v1
kind: Service
metadata:
  labels:
    service: test-server
  name: test-server
spec:
  ports:
  - name: "5021"
    port: 5021
    targetPort: 5021
    protocol: TCP
    nodePort: 30015
  selector:
    service: test-server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: test-server
  name: test-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: test-server
  template:
    metadata:
      labels:
        service: test-server
    spec:
      containers:
      - image: leoadams/test-server:latest
        name: test-server
        ports:
        - containerPort: 5021
          protocol: TCP
        imagePullPolicy: IfNotPresent
        #imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      #restartPolicy: Always